In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os, sys
sys.path.append('/content/drive/MyDrive/CPD_BT')

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import random

import itertools

from bt_cpd import *

import time
import bisect

import pandas as pd

import statsmodels.api as sm
from sklearn import linear_model

from warnings import simplefilter
from sklearn.exceptions import ConvergenceWarning
simplefilter("ignore", category=ConvergenceWarning)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [8]:
T = 4
Delta = 800
m = np.array([Delta] * T)
cp_truth = np.cumsum(m)[:T-1]
print(cp_truth)

n = 20

sub = 0.25

[ 800 1600 2400]


In [9]:
path = '/content/drive/MyDrive/CPD_BT/experiment_random/'
with open(path + 'data_n' + str(n) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_sub' + str(int(100 * sub)) + '.npy', 'rb') as f:
    beta_list = np.load(f)
    X_train_list = np.load(f)
    Y_train_list = np.load(f)
    X_test_list = np.load(f)
    Y_test_list = np.load(f)

In [10]:
X_train_list.shape

(100, 3200, 20)

In [11]:
np.random.seed(0)

grid_n = 90
gamma_list = [20, 40]
lam_list = [0.1]

nt = Delta * T
B = 100

run_time_d = np.zeros(B)
loc_error_d = np.zeros(B)
K_d = np.zeros(B)

cp_best_list = []
param_best_list = []
cp_best_cand_list = []

for b in range(B):
    X_train = X_train_list[b]
    Y_train = Y_train_list[b]
    X_test = X_test_list[b]
    Y_test = Y_test_list[b]

    start_time = time.time()
    dp_fit = dplr_cv_bt(grid_n, lam_list, gamma_list)
    cp_best, param_best, cp_best_cand = dp_fit.fit((Y_train, X_train), (Y_test, X_test))    
    run_time_d[b] = time.time() - start_time
    loc_error_d[b] = cp_distance(cp_best, cp_truth)
    K_d[b] = len(cp_best)

    cp_best_list.append(cp_best)
    param_best_list.append(param_best)
    cp_best_cand_list.append(cp_best_cand)
    print(b)


print('---------- dplr -----------')
print("avg loc error: {0}, avg time: {1}".format(loc_error_d.mean(), run_time_d.mean()))
print("std loc error: {0}, std time: {1}".format(loc_error_d.std(), run_time_d.std()))
print('K < K*: {0}, K = K*: {1}, K > K*: {2}'.format(sum(K_d < T - 1), sum(K_d == T - 1), sum(K_d > T - 1)))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
---------- dplr -----------
avg loc error: inf, avg time: 97.65655762434005
std loc error: nan, std time: 18.74192922753696
K < K*: 82, K = K*: 17, K > K*: 1


/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:230: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


In [12]:
loc_error_d

array([  inf,   inf,  759.,  768.,    7.,   inf,  786.,   inf,   inf,
         91.,  800.,   inf,   91.,  798.,   inf,   inf,   inf,   inf,
        589.,  779.,  877.,  804.,  807.,   20.,   inf,   inf,  115.,
        808.,   inf, 1605.,  800.,  911.,  108.,  759.,  798.,  800.,
       1598.,   inf,  800.,  809.,  812.,   inf,  812., 1039.,   inf,
        876.,  914.,  792.,  809.,   inf,   inf,   inf,  521.,  519.,
        504.,   inf,  804.,   inf,  791.,  800.,   inf,  805.,  789.,
        416., 1456., 1172.,   inf,  796.,   inf, 1031., 1736.,   inf,
        133.,   inf,  264.,  312., 1592.,   inf,  846.,   81.,   44.,
        877.,  794.,   inf,   inf,   inf,   inf,   42.,  102.,   inf,
       1037.,   inf,   inf,    4.,   68.,  816.,   inf,   inf,   inf,
        893.])

In [13]:
cp_best_list

[[],
 [],
 [1559, 2395],
 [832, 2397],
 [793, 1595, 2401],
 [],
 [759, 1614],
 [],
 [],
 [891, 1525, 2399],
 [1600],
 [],
 [798, 1562, 2309],
 [798, 1602],
 [],
 [],
 [],
 [],
 [831, 1811],
 [1579, 2397],
 [1523],
 [796, 2470],
 [1607],
 [806, 1600, 2380],
 [],
 [],
 [795, 1611, 2285],
 [1608],
 [],
 [2405],
 [795, 1600],
 [891, 1489],
 [908, 1513, 2400],
 [686, 2359],
 [757, 1602],
 [1600],
 [107, 802],
 [],
 [1600],
 [791, 2411],
 [1612],
 [],
 [1612],
 [1361],
 [],
 [1676, 2398],
 [1714],
 [1592, 2347],
 [1591],
 [],
 [],
 [],
 [824, 2121, 2396],
 [1319, 1613, 2392],
 [1096, 2400],
 [],
 [1604, 2266],
 [],
 [809, 2535],
 [783, 1600],
 [],
 [1605],
 [578, 1611],
 [1216, 1591, 2393],
 [944],
 [1972],
 [],
 [799, 1604],
 [],
 [1831, 2389],
 [664],
 [],
 [933, 1608, 2389],
 [],
 [747, 1840, 2136, 2395],
 [727, 1566, 2712],
 [808],
 [],
 [800, 1554],
 [805, 1519, 2396],
 [756, 1600, 2386],
 [1523],
 [1594, 2395],
 [],
 [],
 [],
 [],
 [804, 1605, 2358],
 [804, 1702, 2406],
 [],
 [1363],
 

In [14]:
cp_best_cand_list

[array([], dtype=float64),
 array([], dtype=float64),
 array([1575, 2415]),
 array([ 805, 2380]),
 array([ 805, 1610, 2380]),
 array([], dtype=float64),
 array([ 770, 1575]),
 array([], dtype=float64),
 array([], dtype=float64),
 array([ 910, 1575, 2380]),
 array([1575]),
 array([], dtype=float64),
 array([ 805, 1575, 2310]),
 array([805, 980]),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64),
 array([ 805, 1785]),
 array([1610, 2450]),
 array([1505]),
 array([ 770, 2485]),
 array([735]),
 array([ 805, 1610, 2380]),
 array([], dtype=float64),
 array([], dtype=float64),
 array([ 805, 1610, 2345]),
 array([1610]),
 array([], dtype=float64),
 array([2520]),
 array([ 805, 1610]),
 array([ 875, 1575]),
 array([ 910, 1540, 2415]),
 array([ 700, 2345]),
 array([ 770, 1610]),
 array([2415]),
 array([105, 805]),
 array([], dtype=float64),
 array([1575]),
 array([ 770, 2415]),
 array([1610]),
 array([], dtype=float64),
 array([1610]),
 a

In [15]:
import pickle
with open(path + 'dplr_n' + str(n) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_grid' + str(grid_n) + '_sub' + str(int(100 * sub)) + '.pickle', 'wb') as f:
    pickle.dump([beta_list, cp_best_list, param_best_list, cp_best_cand_list, loc_error_d, run_time_d, K_d], f)

In [21]:
loc_error_d[loc_error_d > (T // 2) * Delta] = (T // 2) * Delta

print("avg loc error: {0}, avg time: {1}".format(loc_error_d.mean(), run_time_d.mean()))
print("std loc error: {0}, std time: {1}".format(loc_error_d.std(), run_time_d.std()))
print('K < K*: {0}, K = K*: {1}, K > K*: {2}'.format(sum(K_d < T - 1), sum(K_d == T - 1), sum(K_d > T - 1)))

avg loc error: 1030.45, avg time: 97.65655762434005
std loc error: 544.2957720761755, std time: 18.74192922753696
K < K*: 82, K = K*: 17, K > K*: 1
