In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os, sys
sys.path.append('/content/drive/MyDrive/CPD_BT')

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import random

import itertools

from bt_cpd import *

import time
import bisect

import pandas as pd

import statsmodels.api as sm
from sklearn import linear_model

from warnings import simplefilter
from sklearn.exceptions import ConvergenceWarning
simplefilter("ignore", category=ConvergenceWarning)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [4]:
T = 4
Delta = 800
m = np.array([Delta] * T)
cp_truth = np.cumsum(m)[:T-1]
print(cp_truth)

n = 20

sub = 0.50

[ 800 1600 2400]


In [5]:
path = '/content/drive/MyDrive/CPD_BT/experiment_random/'
with open(path + 'data_n' + str(n) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_sub' + str(int(100 * sub)) + '.npy', 'rb') as f:
    beta_list = np.load(f)
    X_train_list = np.load(f)
    Y_train_list = np.load(f)
    X_test_list = np.load(f)
    Y_test_list = np.load(f)

In [6]:
X_train_list.shape

(100, 3200, 20)

In [7]:
np.random.seed(0)

grid_n = 90
gamma_list = [20, 40]
lam_list = [0.1]

nt = Delta * T
B = 100

run_time_d = np.zeros(B)
loc_error_d = np.zeros(B)
K_d = np.zeros(B)

cp_best_list = []
param_best_list = []
cp_best_cand_list = []

for b in range(B):
    X_train = X_train_list[b]
    Y_train = Y_train_list[b]
    X_test = X_test_list[b]
    Y_test = Y_test_list[b]

    start_time = time.time()
    dp_fit = dplr_cv_bt(grid_n, lam_list, gamma_list)
    cp_best, param_best, cp_best_cand = dp_fit.fit((Y_train, X_train), (Y_test, X_test))    
    run_time_d[b] = time.time() - start_time
    loc_error_d[b] = cp_distance(cp_best, cp_truth)
    K_d[b] = len(cp_best)

    cp_best_list.append(cp_best)
    param_best_list.append(param_best)
    cp_best_cand_list.append(cp_best_cand)
    print(b)


print('---------- dplr -----------')
print("avg loc error: {0}, avg time: {1}".format(loc_error_d.mean(), run_time_d.mean()))
print("std loc error: {0}, std time: {1}".format(loc_error_d.std(), run_time_d.std()))
print('K < K*: {0}, K = K*: {1}, K > K*: {2}'.format(sum(K_d < T - 1), sum(K_d == T - 1), sum(K_d > T - 1)))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
---------- dplr -----------
avg loc error: inf, avg time: 97.06034440994263
std loc error: nan, std time: 10.370942580372569
K < K*: 27, K = K*: 67, K > K*: 6


/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:230: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


In [8]:
loc_error_d

array([  inf,   inf,   19.,   68.,   95.,   13.,   25.,  792.,  178.,
         13.,   19.,  810.,   66.,    7.,   46.,   34.,   24.,  781.,
        831.,  798.,   39.,   35.,  764., 1610.,   57.,  783.,   16.,
        166.,    9.,   inf,   93.,   11.,   24.,  771., 1592.,   inf,
         95.,  607.,   32.,  764.,  489.,  398.,   54.,  107.,    8.,
         83.,  317.,   65.,   47.,   21.,    7.,    5.,   14.,   inf,
         26.,   48.,   55.,  803.,  415.,  184.,   66.,   26.,  859.,
        843.,   65.,  891.,  819.,  119., 1598.,  800.,  492.,   19.,
         inf,  418.,  106.,   78.,   46.,    3.,   25.,   62.,   47.,
         43.,   14.,  203.,   25.,   72.,  118.,  803.,   12.,   12.,
         23.,   63.,    9.,  116.,   25.,   inf,   28.,   44.,  777.,
         92.])

In [9]:
cp_best_list

[[],
 [],
 [783, 1619, 2405],
 [806, 1601, 2468],
 [800, 1505, 2428],
 [799, 1613, 2397],
 [775, 1611, 2388],
 [814, 1608],
 [800, 1422, 2503],
 [787, 1600, 2393],
 [810, 1581, 2405],
 [1610],
 [790, 1666, 2377],
 [793, 1601, 2401],
 [789, 1554, 2405],
 [797, 1597, 2434],
 [795, 1576, 2403],
 [819, 2410],
 [798, 1569],
 [754, 2398],
 [806, 1591, 2361],
 [814, 1565, 2429],
 [796, 2364],
 [790],
 [810, 1651, 2343],
 [811, 1617],
 [793, 1584, 2404],
 [966, 1580, 2389],
 [794, 1598, 2391],
 [],
 [798, 1693, 2400],
 [793, 1592, 2389],
 [788, 1611, 2424],
 [829, 2399],
 [2392],
 [],
 [705, 1618, 2401],
 [752, 1593, 2380, 3007],
 [768, 1589, 2400],
 [754, 1636],
 [1111, 1111, 2372],
 [402, 1621, 2685],
 [800, 1602, 2454],
 [796, 1616, 2293],
 [792, 1597, 2401],
 [717, 1577, 2400],
 [828, 1557, 1917, 2399],
 [865, 1572, 2393],
 [846, 1601, 2447],
 [802, 1604, 2379],
 [796, 1593, 2402],
 [795, 1600, 2401],
 [800, 1586, 2393],
 [],
 [795, 1599, 2374],
 [797, 1648, 2393],
 [754, 1616, 2345],
 [15

In [10]:
cp_best_cand_list

[array([], dtype=float64),
 array([], dtype=float64),
 array([ 805, 1610, 2415]),
 array([ 805, 1575, 2485]),
 array([ 805, 1505, 2415]),
 array([ 805, 1610, 2380]),
 array([ 770, 1610, 2380]),
 array([ 805, 1610]),
 array([ 805, 1400, 2485]),
 array([ 805, 1610, 2380]),
 array([ 665, 1610, 2415]),
 array([2415]),
 array([ 805, 1680, 2380]),
 array([ 805, 1610, 2380]),
 array([ 805, 1540, 2415]),
 array([ 805, 1610, 2450]),
 array([ 805, 1575, 2415]),
 array([ 840, 2380]),
 array([ 805, 1610]),
 array([ 770, 2415]),
 array([ 805, 1575, 2380]),
 array([ 700, 1575, 2380]),
 array([ 245, 2380]),
 array([770]),
 array([ 805, 1645, 2555]),
 array([ 805, 1610]),
 array([ 770, 1575, 2415]),
 array([ 945, 1575, 2380]),
 array([ 805, 1505, 2380]),
 array([], dtype=float64),
 array([ 805, 1575, 2415]),
 array([ 805, 1610, 2380]),
 array([ 875, 1610, 2485]),
 array([ 805, 2415]),
 array([2380]),
 array([], dtype=float64),
 array([ 875, 1610, 2380]),
 array([ 770, 1540, 2380, 2765]),
 array([ 770,

In [11]:
import pickle
with open(path + 'dplr_n' + str(n) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_grid' + str(grid_n) + '_sub' + str(int(100 * sub)) + '.pickle', 'wb') as f:
    pickle.dump([beta_list, cp_best_list, param_best_list, cp_best_cand_list, loc_error_d, run_time_d, K_d], f)

In [18]:
loc_error_d[loc_error_d > (T // 2) * Delta] = (T // 2) * Delta

print("avg loc error: {0}, avg time: {1}".format(loc_error_d.mean(), run_time_d.mean()))
print("std loc error: {0}, std time: {1}".format(loc_error_d.std(), run_time_d.std()))
print('K < K*: {0}, K = K*: {1}, K > K*: {2}'.format(sum(K_d < T - 1), sum(K_d == T - 1), sum(K_d > T - 1)))

avg loc error: 362.84, avg time: 97.06034440994263
std loc error: 502.19804300693966, std time: 10.370942580372569
K < K*: 27, K = K*: 67, K > K*: 6
