In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os, sys
sys.path.append('/content/drive/MyDrive/CPD_BT')

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import random

import itertools

from bt_cpd import *

import time
import bisect

import pandas as pd

import statsmodels.api as sm
from sklearn import linear_model

from warnings import simplefilter
from sklearn.exceptions import ConvergenceWarning
simplefilter("ignore", category=ConvergenceWarning)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
T = 4
Delta = 500
m = np.array([Delta] * T)
cp_truth = np.cumsum(m)[:T-1]
print(cp_truth)

n = 10
beta = np.zeros((T, n))

t = 0.9
kappa = np.log(t / (1 - t))
delta = 1
beta_ref = get_beta_with_gap(n, delta)
beta_ref *= kappa / (np.max(beta_ref) - np.min(beta_ref))
beta[0] = beta_ref[:]
beta[1] = change_type(beta_ref, 1)
beta[2] = change_type(beta_ref, 2)
beta[3] = change_type(beta_ref, 3)

print(max(beta[0]) - min(beta[0]))

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(beta[t] - beta[t - 1])**2)**0.5
print(diff)

[ 500 1000 1500]
2.1972245773362196
[4.43495185 3.86013011 4.43495185]


In [ ]:
np.random.seed(0)

nt = Delta * T
B = 100
X_train_list = np.zeros((B, nt, n))
X_test_list = np.zeros((B, nt, n))
Y_train_list = np.zeros((B, nt))
Y_test_list = np.zeros((B, nt))

for b in range(B):
    nt, Y_train, X_train = generate_data_bt(m, T, beta)
    nt, Y_test, X_test = generate_data_bt(m, T, beta)
    X_train_list[b] = X_train
    Y_train_list[b] = Y_train
    X_test_list[b] = X_test
    Y_test_list[b] = Y_test

In [ ]:
path = '/content/drive/MyDrive/CPD_BT/'
with open(path + 'data_n' + str(n) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '.npy', 'wb') as f:
    np.save(f, X_train_list)
    np.save(f, Y_train_list)
    np.save(f, X_test_list)
    np.save(f, Y_test_list)

In [ ]:
T = 4
Delta = 800
m = np.array([Delta] * T)
cp_truth = np.cumsum(m)[:T-1]
print(cp_truth)

n = 20
beta = np.zeros((T, n))

t = 0.9
kappa = np.log(t / (1 - t))
delta = 1
beta_ref = get_beta_with_gap(n, delta)
beta_ref *= kappa / (np.max(beta_ref) - np.min(beta_ref))
beta[0] = beta_ref[:]
beta[1] = change_type(beta_ref, 1)
beta[2] = change_type(beta_ref, 2)
beta[3] = change_type(beta_ref, 3)

print(max(beta[0]) - min(beta[0]))

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(beta[t] - beta[t - 1])**2)**0.5
print(diff)

[ 800 1600 2400]
2.1972245773362196
[5.96433002 5.17173002 5.96433002]


In [ ]:
np.random.seed(0)

nt = Delta * T
B = 100
X_train_list = np.zeros((B, nt, n))
X_test_list = np.zeros((B, nt, n))
Y_train_list = np.zeros((B, nt))
Y_test_list = np.zeros((B, nt))

for b in range(B):
    nt, Y_train, X_train = generate_data_bt(m, T, beta)
    nt, Y_test, X_test = generate_data_bt(m, T, beta)
    X_train_list[b] = X_train
    Y_train_list[b] = Y_train
    X_test_list[b] = X_test
    Y_test_list[b] = Y_test

In [ ]:
path = '/content/drive/MyDrive/CPD_BT/'
with open(path + 'data_n' + str(n) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '.npy', 'wb') as f:
    np.save(f, X_train_list)
    np.save(f, Y_train_list)
    np.save(f, X_test_list)
    np.save(f, Y_test_list)

In [ ]:
T = 4
Delta = 2000
m = np.array([Delta] * T)
cp_truth = np.cumsum(m)[:T-1]
print(cp_truth)

n = 100
beta = np.zeros((T, n))

t = 0.9
kappa = np.log(t / (1 - t))
delta = 1
beta_ref = get_beta_with_gap(n, delta)
beta_ref *= kappa / (np.max(beta_ref) - np.min(beta_ref))
beta[0] = beta_ref[:]
beta[1] = change_type(beta_ref, 1)
beta[2] = change_type(beta_ref, 2)
beta[3] = change_type(beta_ref, 3)

print(max(beta[0]) - min(beta[0]))

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(beta[t] - beta[t - 1])**2)**0.5
print(diff)

[2000 4000 6000]
2.1972245773362196
[12.81317951 11.09709382 12.81317951]


In [ ]:
np.random.seed(0)

nt = Delta * T
B = 100
X_train_list = np.zeros((B, nt, n))
X_test_list = np.zeros((B, nt, n))
Y_train_list = np.zeros((B, nt))
Y_test_list = np.zeros((B, nt))

for b in range(B):
    nt, Y_train, X_train = generate_data_bt(m, T, beta)
    nt, Y_test, X_test = generate_data_bt(m, T, beta)
    X_train_list[b] = X_train
    Y_train_list[b] = Y_train
    X_test_list[b] = X_test
    Y_test_list[b] = Y_test

In [ ]:
path = '/content/drive/MyDrive/CPD_BT/'
with open(path + 'data_n' + str(n) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '.npy', 'wb') as f:
    np.save(f, X_train_list)
    np.save(f, Y_train_list)
    np.save(f, X_test_list)
    np.save(f, Y_test_list)

In [ ]:
T = 2
Delta = 500
m = np.array([Delta] * T)
cp_truth = np.cumsum(m)[:T-1]
print(cp_truth)


n = 200
beta = np.zeros((T, n))

t = 0.9
kappa = np.log(t / (1 - t))
delta = 1
beta_ref = get_beta_with_gap(n, delta)
beta_ref *= kappa / (np.max(beta_ref) - np.min(beta_ref))
beta[0] = beta_ref[:]
beta[1] = change_type(beta_ref, 1)

print(max(beta[0]) - min(beta[0]))

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(beta[t] - beta[t - 1])**2)**0.5
print(diff)

[500]
2.1972245773362196
[18.03019025]


In [ ]:
np.random.seed(0)

nt = Delta * T
B = 100
X_train_list = np.zeros((B, nt, n))
X_test_list = np.zeros((B, nt, n))
Y_train_list = np.zeros((B, nt))
Y_test_list = np.zeros((B, nt))

for b in range(B):
    nt, Y_train, X_train = generate_data_bt(m, T, beta)
    nt, Y_test, X_test = generate_data_bt(m, T, beta)
    X_train_list[b] = X_train
    Y_train_list[b] = Y_train
    X_test_list[b] = X_test
    Y_test_list[b] = Y_test

In [ ]:
path = '/content/drive/MyDrive/CPD_BT/'
with open(path + 'data_n' + str(n) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '.npy', 'wb') as f:
    np.save(f, X_train_list)
    np.save(f, Y_train_list)
    np.save(f, X_test_list)
    np.save(f, Y_test_list)

In [4]:
T = 3
Delta = 1000
m = np.array([Delta] * T)
cp_truth = np.cumsum(m)[:T-1]
print(cp_truth)

n = 100
beta = np.zeros((T, n))

t = 0.9
kappa = np.log(t / (1 - t))
delta = 1
beta_ref = get_beta_with_gap(n, delta)
beta_ref *= kappa / (np.max(beta_ref) - np.min(beta_ref))
beta[0] = beta_ref[:]
beta[1] = change_type(beta_ref, 1)
beta[2] = change_type(beta_ref, 2)

print(max(beta[0]) - min(beta[0]))

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(beta[t] - beta[t - 1])**2)**0.5
print(diff)

[1000 2000]
2.1972245773362196
[12.81317951 11.09709382]


In [5]:
np.random.seed(0)

nt = Delta * T
B = 100
X_train_list = np.zeros((B, nt, n))
X_test_list = np.zeros((B, nt, n))
Y_train_list = np.zeros((B, nt))
Y_test_list = np.zeros((B, nt))

for b in range(B):
    nt, Y_train, X_train = generate_data_bt(m, T, beta)
    nt, Y_test, X_test = generate_data_bt(m, T, beta)
    X_train_list[b] = X_train
    Y_train_list[b] = Y_train
    X_test_list[b] = X_test
    Y_test_list[b] = Y_test

In [6]:
path = '/content/drive/MyDrive/CPD_BT/'
with open(path + 'data_n' + str(n) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '.npy', 'wb') as f:
    np.save(f, X_train_list)
    np.save(f, Y_train_list)
    np.save(f, X_test_list)
    np.save(f, Y_test_list)